FROM qeacourse/robodocker:simulatedgzweb
MAINTAINER Paul Ruvolo Paul.Ruvolo@olin.edu

CMD /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch neato_node bringup_minimal.launch host:=$HOST use_udp:=false"

